### ISSUE TITLE
Re-run dry model

### ISSUE THREAD

**Issue by luminoctum** [mayaafields/practice_coding#5]
Here's the geometric setting to use for the dry simulation:

- Vertical extent, 300 km
- Number of vertical grids, 48
- Horizontal extent, 1200 km
- Number of horizontal grids, 96
- Pressure at the topmost grid, 1 bar
- Temperature at the topmost grid, 166 K
- Running time, 1000 days
- Domain decomposition, 8 cores
- No water and ammonia, no condensate particles
- Remove water and ammonia thermodynamics in the input file
- Remove nvapor in the configuration
- Keep the ideal gas constant `Rd` in the thermodynamics section

The vertical resolution is 6.25 km and the horizontal resolution is 12.5 km. This ensures that sound waves are properly damped out.

Once you have modified the input file to the setting, reply to this issue. I'll take a look at the input file. If it is OK, you can submit the job and re-run the dry model.

**Comment by mayaafields** [comment]
I think that I have updated the input file. The only thing I am unsure about is which values to get rid of under thermodynamics. the path to the files is 

/home/mafields/CylconeDiagnostics/jupiter_runs/jupiter_modelruns/240622_1000_64256_c8_1e5_dry/jupiter2d_dry.inp

**Comment by luminoctum** [comment]
- These parameters under thermodynamics are related to vapors. So they are not needed.
```
eps1        = 8.18    8.18    8.18
beta1       = 0.      24.85   24.85
rcp1        = 0.15    0.33    0.33
Ttriple1    = 273.16
Ptriple1    = 611.7
```
- Your meshblock setting is wrong.
- Remove 
```
<particles>
<chemistry>
```
- Remove
```
qvapor1
qvapor2
```
- Remove
```
--ngridmax=11
```
Also, pull my new updates.

**Comment by mayaafields** [comment]
I think that I have fixed the input file now.
